plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT' apply false
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.4.1" // required for VanillaGradle and NeoForge to work together?
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT' apply false
    id 'net.darkhax.curseforgegradle' version "${cursegradle_version}" apply false // curseforge publishing
    id "com.modrinth.minotaur" version "2.+" apply false // modrinth publishing
}

subprojects {
    configurations.all {
        resolutionStrategy {
            cacheChangingModulesFor 60, 'seconds'
            cacheDynamicVersionsFor 60, 'seconds'
        }
    }
    // Pass the raw project version string as an extra property to each subproject
    // since the version property will be overwritten by the complete version string
    ext {
        rawVersion = project.version
    }
}

task publishCurseForge(dependsOn: [':Fabric:publishCurseForgeFabric', ':NeoForge:publishCurseForgeNeoForge']) {
}
task publishModrinth(dependsOn: [':Fabric:modrinth', ':NeoForge:modrinth']) {
}
task publishCurseAndModrinth(dependsOn: ['publishCurseForge', 'publishModrinth']) {
}