# Project
version=4.1.0
java_version=25

# Metadata
mod_name=YungsBetterCaves
mod_full_name=YUNG's Better Caves
mod_id=bettercaves
mod_author=YUNGNICKYOUNG
mod_description=A complete overhaul of Minecraft's cave generation!
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.bettercaves
mc_version=26.1.2
mc_version_range=[26.1,)
mc_version_range_fabric=>=26.1
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
mc_version_neo_form=26.1.2-1

# CurseForge/Modrinth Publishing
cursegradle_version=1.1.24
compatible_versions=26.1.1,26.1.2
curseforge_project_id_fabric=408465
curseforge_project_id_neoforge=340583
modrinth_project_id=Dfu00ggU
debug_publish=true

# Common
yungsapi_version=6.1.0

# Fabric
fabric_version=0.150.0
fabric_loader_version=0.18.6
clothconfig_version_fabric=26.1.154
modmenu_version_fabric=18.0.0-beta.1

# NeoForge
neoforge_version=26.1.2.75
neoforge_version_range=[26.1.2.75,)
neoforge_loader_version_range=[4,)

# Credentials for publishing. Gets overwritten with global gradle.properties.
# Hands off, pal. This is for YUNG only.
curseforgeApiKey=""
modrinthToken=""

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
