# Project
version=3.1.5
java_version=21

# Metadata
mod_name=YungsBetterCaves
mod_full_name=YUNG's Better Caves
mod_id=bettercaves
mod_author=YUNGNICKYOUNG
mod_description=A complete overhaul of Minecraft's cave generation!
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.bettercaves
mc_version=1.21.1
mc_version_range=[1.21, 1.22)
mc_version_range_fabric=>=1.21
parchment_minecraft=1.21
parchment_version=2024.06.23

# CurseForge/Modrinth Publishing
curseforgegradle_version=1.1.24
compatible_versions=1.21,1.21.1
curseforge_project_id_forge=340583
curseforge_project_id_fabric=408465
curseforge_project_id_neoforge=340583
modrinth_project_id=yungs-better-caves
debug_publish=true

# Common
yungsapi_version=5.1.5

# Forge
forge_version=52.0.17
forge_loader_version_range=[51,)

# Fabric
fabric_version=0.102.0
fabric_loader_version=0.15.11
clothconfig_version_fabric=15.0.140
modmenu_version_fabric=11.0.2

# NeoForge
neoforge_version=21.1.66
neoforge_version_range=[21.0.0,)
neoforge_loader_version_range=[4,)

# Credentials for publishing. Gets overwritten with global gradle.properties.
curseforgeApiKey=""
modrinthToken=""

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

